# Generated by Django 5.0.1 on 2024-01-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('introduction', models.CharField(max_length=300, verbose_name='Introduction')),
                ('article_copy', models.TextField(verbose_name='Copy')),
                ('cover_img', models.ImageField(upload_to='files/covers')),
                ('date', models.DateTimeField(verbose_name='Publishing date')),
            ],
        ),
    ]
